import { useMemo, useState, type FormEvent } from "react";
import { Archive, MessageCircleMore, RefreshCw, Search, Send } from "lucide-react";
import { AppButton } from "../../components/common/AppButton";
import { AppCard } from "../../components/common/AppCard";
import { useCustomers } from "../customers/useCustomers";
import { useMessages } from "./useMessages";
const format=(v:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
export function MessagesPage(){
 const {customers}=useCustomers(); const {threads,messages,activeThreadId,setActiveThreadId,loading,loadingMessages,error,refresh,send,archive}=useMessages();
 const [query,setQuery]=useState(""),[body,setBody]=useState(""),[newCustomerId,setNewCustomerId]=useState(""),[sending,setSending]=useState(false),[notice,setNotice]=useState("");
 const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c])),[customers]); const activeThread=threads.find(t=>t.id===activeThreadId)??null; const activeCustomer=activeThread?customerMap.get(activeThread.customerId):customerMap.get(newCustomerId);
 const filtered=threads.filter(t=>{const c=customerMap.get(t.customerId);return [c?.firstName,c?.lastName,c?.mobilePhone,t.subject].join(" ").toLowerCase().includes(query.trim().toLowerCase());}); const unread=threads.reduce((n,t)=>n+t.unreadCount,0);
 const show=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2200)};
 async function submit(e:FormEvent){e.preventDefault();const customerId=activeThread?.customerId??newCustomerId;if(!customerId)return show("Select a customer first.");if(!body.trim())return;setSending(true);try{await send(customerId,body,activeThread?.id);setBody("");setNewCustomerId("");show("Message sent.");}catch(err){show(err instanceof Error?err.message:"Unable to send message.");}finally{setSending(false);}}
 return <div className="messages-page"><section className="page-toolbar"><div className="page-head"><span className="eyebrow">Client communication</span><h1>Messages</h1><p>Keep customer conversations connected to profiles and pets.</p></div><AppButton variant="secondary" onClick={()=>void refresh()}><RefreshCw size={17}/> Refresh</AppButton></section>{notice&&<div className="success-notice">{notice}</div>}
 <section className="message-summary-grid"><AppCard className="summary-card"><MessageCircleMore size={22}/><div><span>Open conversations</span><strong>{threads.length}</strong></div></AppCard><AppCard className="summary-card"><span className="summary-emoji">📩</span><div><span>Unread messages</span><strong>{unread}</strong></div></AppCard></section>
 <section className="message-workspace"><aside className="message-thread-panel"><div className="module-search"><Search size={18}/><input aria-label="Search messages" placeholder="Search customer or conversation..." value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="field new-conversation"><span>Start new conversation</span><select value={newCustomerId} onChange={e=>{setNewCustomerId(e.target.value);setActiveThreadId("");}}><option value="">Select customer</option>{customers.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label><div className="thread-list">{loading&&<div className="module-state compact"><div className="paw-loader">🐾</div></div>}{!loading&&error&&<div className="form-error">{error}</div>}{!loading&&filtered.map(t=>{const c=customerMap.get(t.customerId);return <button type="button" key={t.id} className={`thread-item ${t.id===activeThreadId?"is-active":""}`} onClick={()=>{setNewCustomerId("");setActiveThreadId(t.id);}}><div className="thread-avatar">{(c?.firstName?.[0]??"?").toUpperCase()}</div><div className="thread-copy"><div><strong>{c?`${c.firstName} ${c.lastName}`:"Customer"}</strong><time>{format(t.lastMessageAt)}</time></div><span>{t.subject}</span></div>{t.unreadCount>0&&<span className="unread-badge">{t.unreadCount}</span>}</button>})}</div></aside>
 <AppCard className="conversation-panel">{activeThread||newCustomerId?<><header className="conversation-head"><div><span className="eyebrow">Conversation</span><h2>{activeCustomer?`${activeCustomer.firstName} ${activeCustomer.lastName}`:"New conversation"}</h2></div>{activeThread&&<button className="icon-button" onClick={()=>void archive(activeThread.id)} aria-label="Archive conversation"><Archive size={18}/></button>}</header><div className="conversation-body">{loadingMessages&&<div className="module-state compact"><div className="paw-loader">🐾</div></div>}{!loadingMessages&&messages.length===0&&<div className="conversation-empty"><span>🐾</span><h3>Start the conversation</h3><p>Send the first message to this customer.</p></div>}{!loadingMessages&&messages.map(m=><div key={m.id} className={`message-bubble-row ${m.direction==="Outbound"?"outbound":"inbound"}`}><div className="message-bubble"><p>{m.body}</p><div><time>{format(m.sentAt)}</time><span>{m.status}</span></div></div></div>)}</div><form className="message-composer" onSubmit={submit}><textarea aria-label="Message" placeholder="Type a message..." value={body} onChange={e=>setBody(e.target.value)} rows={3}/><AppButton disabled={sending||!body.trim()}><Send size={17}/>{sending?"Sending...":"Send message"}</AppButton></form></>:<div className="conversation-empty large"><span>💬</span><h3>Select a conversation</h3><p>Choose a customer thread or start a new conversation.</p></div>}</AppCard></section></div>;
}
