import { useMemo, useState, type FormEvent } from "react";
import { BarChart3, Megaphone, RefreshCw, Search, Star, UserPlus, Users } from "lucide-react";
import { AppButton } from "../../components/common/AppButton";
import { AppCard } from "../../components/common/AppCard";
import { useCustomers } from "../customers/useCustomers";
import type { CampaignInput, CustomerSegment, LeadInput } from "./crmTypes";
import { useCrm } from "./useCrm";

const segments: Array<CustomerSegment|"All Customers">=["All Customers","VIP","Loyal","New","At Risk","Dormant","Prospect"];
const campaignBlank:CampaignInput={name:"",channel:"Both",status:"Draft",audienceSegment:"All Customers",subject:"",message:"",scheduledAt:""};
const leadBlank:LeadInput={firstName:"",lastName:"",email:"",mobilePhone:"",source:"Website",status:"New",notes:""};
export function CrmMarketingPage(){
 const{customers}=useCustomers();const{profiles,campaigns,leads,loading,error,refresh,addCampaign,addLead,setCampaignStatus}=useCrm();
 const[tab,setTab]=useState<'customers'|'campaigns'|'leads'>('customers');const[query,setQuery]=useState('');const[segment,setSegment]=useState('All');const[showCampaign,setShowCampaign]=useState(false);const[showLead,setShowLead]=useState(false);const[campaign,setCampaign]=useState<CampaignInput>(campaignBlank);const[lead,setLead]=useState<LeadInput>(leadBlank);const[notice,setNotice]=useState('');
 const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c])),[customers]);
 const filteredProfiles=profiles.filter(p=>{const c=customerMap.get(p.customerId);const h=[c?.firstName,c?.lastName,c?.email,p.segment,p.tags.join(' ')].join(' ').toLowerCase();return h.includes(query.toLowerCase())&&(segment==='All'||p.segment===segment)});
 const totalLtv=profiles.reduce((s,p)=>s+p.lifetimeValue,0);const avgLtv=profiles.length?totalLtv/profiles.length:0;const conversions=campaigns.reduce((s,c)=>s+c.convertedCount,0);const roi=campaigns.reduce((s,c)=>s+c.revenueAttributed,0);
 function show(m:string){setNotice(m);setTimeout(()=>setNotice(''),2200)}
 async function saveCampaign(e:FormEvent){e.preventDefault();await addCampaign(campaign);setCampaign(campaignBlank);setShowCampaign(false);show('Campaign created.')}
 async function saveLead(e:FormEvent){e.preventDefault();await addLead(lead);setLead(leadBlank);setShowLead(false);show('Lead added.')}
 return <div className="crm-page">
  <section className="page-toolbar"><div className="page-head"><span className="eyebrow">Growth center</span><h1>CRM & Marketing</h1><p>Understand customer value, manage leads, and run targeted campaigns.</p></div><div className="toolbar-actions"><AppButton variant="secondary" onClick={()=>void refresh()}><RefreshCw size={17}/>Refresh</AppButton><AppButton onClick={()=>setShowCampaign(true)}><Megaphone size={17}/>New campaign</AppButton></div></section>
  {notice&&<div className="success-notice">{notice}</div>}
  <section className="appointment-summary-grid"><AppCard className="summary-card"><Users size={22}/><div><span>CRM profiles</span><strong>{profiles.length}</strong></div></AppCard><AppCard className="summary-card"><Star size={22}/><div><span>Average lifetime value</span><strong>${avgLtv.toFixed(0)}</strong></div></AppCard><AppCard className="summary-card"><BarChart3 size={22}/><div><span>Campaign conversions</span><strong>{conversions}</strong></div></AppCard><AppCard className="summary-card"><span className="summary-emoji">💰</span><div><span>Attributed revenue</span><strong>${roi.toFixed(0)}</strong></div></AppCard></section>
  <div className="crm-tabs"><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}>Customer CRM</button><button className={tab==='campaigns'?'active':''} onClick={()=>setTab('campaigns')}>Campaigns</button><button className={tab==='leads'?'active':''} onClick={()=>setTab('leads')}>Leads</button></div>
  {loading&&<div className="module-state"><div className="paw-loader">🐾</div></div>}{error&&<div className="form-error">{error}</div>}
  {!loading&&tab==='customers'&&<><section className="module-controls"><div className="module-search"><Search size={18}/><input placeholder="Search customer, tag, or segment..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={segment} onChange={e=>setSegment(e.target.value)}><option>All</option>{segments.slice(1).map(s=><option key={s}>{s}</option>)}</select></section><section className="crm-customer-grid">{filteredProfiles.map(p=>{const c=customerMap.get(p.customerId);return <AppCard className="crm-customer-card" key={p.id}><div className="crm-card-head"><div className="crm-avatar">{c?.firstName?.[0]??'?'}</div><div><h3>{c?`${c.firstName} ${c.lastName}`:'Customer'}</h3><span>{p.segment}{p.isVip?' · VIP':''}</span></div><strong>${p.lifetimeValue.toFixed(0)}</strong></div><div className="crm-stats"><div><span>Total visits</span><b>{p.totalVisits}</b></div><div><span>Grooming</span><b>{p.groomingVisits}</b></div><div><span>Boarding</span><b>{p.boardingVisits}</b></div></div><div className="crm-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><p>{p.internalNotes||'No internal notes.'}</p></AppCard>})}</section></>}
  {!loading&&tab==='campaigns'&&<section className="campaign-grid">{campaigns.map(c=><AppCard className="campaign-card" key={c.id}><div className="campaign-head"><div><span className="status-chip">{c.status}</span><h3>{c.name}</h3><p>{c.channel} · {c.audienceSegment}</p></div><select value={c.status} onChange={e=>void setCampaignStatus(c.id,e.target.value as typeof c.status)}>{['Draft','Scheduled','Active','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></div><p>{c.message}</p><div className="campaign-metrics"><span>Sent <b>{c.sentCount}</b></span><span>Opened <b>{c.openedCount}</b></span><span>Clicks <b>{c.clickedCount}</b></span><span>Conversions <b>{c.convertedCount}</b></span><span>Revenue <b>${c.revenueAttributed}</b></span></div></AppCard>)}</section>}
  {!loading&&tab==='leads'&&<><div className="lead-actions"><AppButton onClick={()=>setShowLead(true)}><UserPlus size={17}/>Add lead</AppButton></div><section className="lead-table card">{leads.map(l=><div className="lead-row" key={l.id}><div className="crm-avatar">{l.firstName[0]}</div><div><strong>{l.firstName} {l.lastName}</strong><span>{l.email||l.mobilePhone}</span></div><span>{l.source}</span><span className="status-chip">{l.status}</span><p>{l.notes}</p></div>)}</section></>}
  {showCampaign&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setShowCampaign(false)}/><form className="module-modal" onSubmit={saveCampaign}><div className="modal-head"><h2>New campaign</h2></div><div className="form-grid two-column"><label className="field"><span>Name</span><input required value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/></label><label className="field"><span>Channel</span><select value={campaign.channel} onChange={e=>setCampaign({...campaign,channel:e.target.value as CampaignInput['channel']})}><option>Email</option><option>SMS</option><option>Both</option></select></label><label className="field"><span>Audience</span><select value={campaign.audienceSegment} onChange={e=>setCampaign({...campaign,audienceSegment:e.target.value as CampaignInput['audienceSegment']})}>{segments.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Schedule</span><input type="datetime-local" value={campaign.scheduledAt} onChange={e=>setCampaign({...campaign,scheduledAt:e.target.value})}/></label><label className="field full"><span>Subject</span><input value={campaign.subject} onChange={e=>setCampaign({...campaign,subject:e.target.value})}/></label><label className="field full"><span>Message</span><textarea required rows={5} value={campaign.message} onChange={e=>setCampaign({...campaign,message:e.target.value})}/></label></div><div className="modal-actions"><AppButton type="button" variant="secondary" onClick={()=>setShowCampaign(false)}>Cancel</AppButton><AppButton>Create campaign</AppButton></div></form></div>}
  {showLead&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setShowLead(false)}/><form className="module-modal" onSubmit={saveLead}><div className="modal-head"><h2>Add lead</h2></div><div className="form-grid two-column"><label className="field"><span>First name</span><input required value={lead.firstName} onChange={e=>setLead({...lead,firstName:e.target.value})}/></label><label className="field"><span>Last name</span><input required value={lead.lastName} onChange={e=>setLead({...lead,lastName:e.target.value})}/></label><label className="field"><span>Email</span><input type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/></label><label className="field"><span>Mobile</span><input value={lead.mobilePhone} onChange={e=>setLead({...lead,mobilePhone:e.target.value})}/></label><label className="field"><span>Source</span><input value={lead.source} onChange={e=>setLead({...lead,source:e.target.value})}/></label><label className="field full"><span>Notes</span><textarea rows={3} value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})}/></label></div><div className="modal-actions"><AppButton type="button" variant="secondary" onClick={()=>setShowLead(false)}>Cancel</AppButton><AppButton>Add lead</AppButton></div></form></div>}
 </div>
}
