import { isSupabaseConfigured, supabase } from "../../lib/supabaseClient";
import type { CampaignInput, CrmProfile, Lead, LeadInput, MarketingCampaign } from "./crmTypes";

const PROFILES_KEY = "wpms-demo-crm-profiles";
const CAMPAIGNS_KEY = "wpms-demo-marketing-campaigns";
const LEADS_KEY = "wpms-demo-crm-leads";

const now = new Date().toISOString();
const seedProfiles: CrmProfile[] = [
  { id:"crm-1", customerId:"demo-customer-1", segment:"VIP", lifetimeValue:2840, totalVisits:31, groomingVisits:24, boardingVisits:7, lastVisitAt:now, nextRecommendedVisit:new Date(Date.now()+28*86400000).toISOString(), referralSource:"Customer Referral", tags:["VIP","Golden Retriever","Monthly Groom"], internalNotes:"Prefers Ashley and weekday mornings.", isVip:true, createdAt:now, updatedAt:now },
  { id:"crm-2", customerId:"demo-customer-2", segment:"Loyal", lifetimeValue:1465, totalVisits:18, groomingVisits:12, boardingVisits:6, lastVisitAt:new Date(Date.now()-14*86400000).toISOString(), nextRecommendedVisit:new Date(Date.now()+20*86400000).toISOString(), referralSource:"Google", tags:["Boarding","Photo Updates"], internalNotes:"Send boarding photo updates twice daily.", isVip:false, createdAt:now, updatedAt:now },
];
const seedCampaigns: MarketingCampaign[] = [
  { id:"campaign-1", name:"Summer Grooming Refresh", channel:"Both", status:"Completed", audienceSegment:"Loyal", subject:"Fresh summer coat for your best friend", message:"Book a summer grooming package and receive a complimentary nail trim.", scheduledAt:new Date(Date.now()-14*86400000).toISOString(), sentCount:126, openedCount:78, clickedCount:31, convertedCount:18, revenueAttributed:1530, createdAt:now, updatedAt:now },
  { id:"campaign-2", name:"We Miss You", channel:"SMS", status:"Scheduled", audienceSegment:"Dormant", subject:"", message:"We miss seeing you and your pet! Reply BOOK to reserve your next visit.", scheduledAt:new Date(Date.now()+2*86400000).toISOString(), sentCount:0, openedCount:0, clickedCount:0, convertedCount:0, revenueAttributed:0, createdAt:now, updatedAt:now },
];
const seedLeads: Lead[] = [
  { id:"lead-1", firstName:"Megan", lastName:"Turner", email:"megan@example.com", mobilePhone:"850-555-0198", source:"Website", status:"New", notes:"Asked about puppy grooming packages.", createdAt:now, updatedAt:now },
];

function read<T>(key:string, seed:T[]):T[]{ const raw=localStorage.getItem(key); if(!raw){localStorage.setItem(key,JSON.stringify(seed));return seed;} return JSON.parse(raw) as T[]; }
function write<T>(key:string, items:T[]){ localStorage.setItem(key,JSON.stringify(items)); }

function profileFromRow(r:Record<string,unknown>):CrmProfile{return {id:String(r.id),customerId:String(r.customer_id),segment:String(r.segment) as CrmProfile['segment'],lifetimeValue:Number(r.lifetime_value??0),totalVisits:Number(r.total_visits??0),groomingVisits:Number(r.grooming_visits??0),boardingVisits:Number(r.boarding_visits??0),lastVisitAt:String(r.last_visit_at??''),nextRecommendedVisit:String(r.next_recommended_visit??''),referralSource:String(r.referral_source??''),tags:Array.isArray(r.tags)?r.tags.map(String):[],internalNotes:String(r.internal_notes??''),isVip:Boolean(r.is_vip),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function campaignFromRow(r:Record<string,unknown>):MarketingCampaign{return {id:String(r.id),name:String(r.name),channel:String(r.channel) as MarketingCampaign['channel'],status:String(r.status) as MarketingCampaign['status'],audienceSegment:String(r.audience_segment) as MarketingCampaign['audienceSegment'],subject:String(r.subject??''),message:String(r.message??''),scheduledAt:String(r.scheduled_at??''),sentCount:Number(r.sent_count??0),openedCount:Number(r.opened_count??0),clickedCount:Number(r.clicked_count??0),convertedCount:Number(r.converted_count??0),revenueAttributed:Number(r.revenue_attributed??0),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function leadFromRow(r:Record<string,unknown>):Lead{return {id:String(r.id),firstName:String(r.first_name),lastName:String(r.last_name),email:String(r.email??''),mobilePhone:String(r.mobile_phone??''),source:String(r.source??''),status:String(r.status) as Lead['status'],notes:String(r.notes??''),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}

export async function listCrmProfiles(){if(!isSupabaseConfigured)return read(PROFILES_KEY,seedProfiles);const{data,error}=await supabase.from('crm_profiles').select('*').order('lifetime_value',{ascending:false});if(error)throw error;return(data??[]).map(profileFromRow)}
export async function listCampaigns(){if(!isSupabaseConfigured)return read(CAMPAIGNS_KEY,seedCampaigns).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const{data,error}=await supabase.from('marketing_campaigns').select('*').order('created_at',{ascending:false});if(error)throw error;return(data??[]).map(campaignFromRow)}
export async function listLeads(){if(!isSupabaseConfigured)return read(LEADS_KEY,seedLeads);const{data,error}=await supabase.from('crm_leads').select('*').order('created_at',{ascending:false});if(error)throw error;return(data??[]).map(leadFromRow)}
export async function createCampaign(input:CampaignInput){if(!isSupabaseConfigured){const item:MarketingCampaign={...input,id:crypto.randomUUID(),sentCount:0,openedCount:0,clickedCount:0,convertedCount:0,revenueAttributed:0,createdAt:now,updatedAt:now};write(CAMPAIGNS_KEY,[item,...read(CAMPAIGNS_KEY,seedCampaigns)]);return item;}const{data,error}=await supabase.from('marketing_campaigns').insert({name:input.name,channel:input.channel,status:input.status,audience_segment:input.audienceSegment,subject:input.subject||null,message:input.message,scheduled_at:input.scheduledAt||null}).select('*').single();if(error)throw error;return campaignFromRow(data)}
export async function createLead(input:LeadInput){if(!isSupabaseConfigured){const item:Lead={...input,id:crypto.randomUUID(),createdAt:now,updatedAt:now};write(LEADS_KEY,[item,...read(LEADS_KEY,seedLeads)]);return item;}const{data,error}=await supabase.from('crm_leads').insert({first_name:input.firstName,last_name:input.lastName,email:input.email||null,mobile_phone:input.mobilePhone||null,source:input.source||null,status:input.status,notes:input.notes||null}).select('*').single();if(error)throw error;return leadFromRow(data)}
export async function updateCampaignStatus(id:string,status:MarketingCampaign['status']){if(!isSupabaseConfigured){const items=read(CAMPAIGNS_KEY,seedCampaigns);const item=items.find(x=>x.id===id);if(!item)throw new Error('Campaign not found.');const updated={...item,status,updatedAt:new Date().toISOString()};write(CAMPAIGNS_KEY,items.map(x=>x.id===id?updated:x));return updated;}const{data,error}=await supabase.from('marketing_campaigns').update({status}).eq('id',id).select('*').single();if(error)throw error;return campaignFromRow(data)}
