import { isSupabaseConfigured, supabase } from "../../lib/supabaseClient";
import type { InventoryItem, InventoryItemInput } from "./inventoryTypes";
const KEY = "wpms-demo-inventory";
const seed: InventoryItem[] = [
 {id:"inv-1",name:"Oatmeal Lavender Shampoo",sku:"SH-100",barcode:"",category:"Shampoo",vendor:"Pet Supply Co.",quantityOnHand:8,reorderLevel:10,unitCost:8.5,retailPrice:18,status:"Active",notes:"Popular sensitive-skin formula.",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
 {id:"inv-2",name:"Blueberry Facial",sku:"GR-210",barcode:"",category:"Grooming Supply",vendor:"Groom Pro",quantityOnHand:14,reorderLevel:5,unitCost:6,retailPrice:15,status:"Active",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
 {id:"inv-3",name:"Dental Chews 6-Pack",sku:"RT-320",barcode:"",category:"Retail",vendor:"Happy Pet Wholesale",quantityOnHand:4,reorderLevel:6,unitCost:5.25,retailPrice:12.99,status:"Active",notes:"Front-counter retail item.",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}
];
function read(){const raw=localStorage.getItem(KEY); if(!raw){localStorage.setItem(KEY,JSON.stringify(seed)); return seed;} return JSON.parse(raw) as InventoryItem[];}
function write(items:InventoryItem[]){localStorage.setItem(KEY,JSON.stringify(items));}
function fromRow(r:Record<string,unknown>):InventoryItem{return {id:String(r.id),name:String(r.name??""),sku:String(r.sku??""),barcode:String(r.barcode??""),category:String(r.category??"Other") as InventoryItem["category"],vendor:String(r.vendor??""),quantityOnHand:Number(r.quantity_on_hand??0),reorderLevel:Number(r.reorder_level??0),unitCost:Number(r.unit_cost??0),retailPrice:Number(r.retail_price??0),status:String(r.status??"Active") as InventoryItem["status"],notes:String(r.notes??""),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function toRow(i:InventoryItemInput){return {name:i.name.trim(),sku:i.sku.trim(),barcode:i.barcode.trim()||null,category:i.category,vendor:i.vendor.trim()||null,quantity_on_hand:i.quantityOnHand,reorder_level:i.reorderLevel,unit_cost:i.unitCost,retail_price:i.retailPrice,status:i.status,notes:i.notes.trim()||null}}
export async function listInventory(){if(!isSupabaseConfigured)return read().sort((a,b)=>a.name.localeCompare(b.name)); const {data,error}=await supabase.from("inventory_items").select("*").order("name"); if(error)throw error; return (data??[]).map(fromRow)}
export async function createInventoryItem(input:InventoryItemInput){if(!isSupabaseConfigured){const now=new Date().toISOString(); const item={...input,id:crypto.randomUUID(),createdAt:now,updatedAt:now}; write([...read(),item]); return item;} const {data,error}=await supabase.from("inventory_items").insert(toRow(input)).select("*").single(); if(error)throw error; return fromRow(data)}
export async function updateInventoryItem(id:string,input:InventoryItemInput){if(!isSupabaseConfigured){const items=read(); const old=items.find(x=>x.id===id); if(!old)throw new Error("Inventory item not found."); const item={...old,...input,updatedAt:new Date().toISOString()}; write(items.map(x=>x.id===id?item:x)); return item;} const {data,error}=await supabase.from("inventory_items").update(toRow(input)).eq("id",id).select("*").single(); if(error)throw error; return fromRow(data)}
