import { useMemo, useState, type FormEvent } from "react";
import { Gift, RefreshCw, Search, Sparkles, Star, Users } from "lucide-react";
import { AppButton } from "../../components/common/AppButton";
import { AppCard } from "../../components/common/AppCard";
import { useCustomers } from "../customers/useCustomers";
import { useMemberships } from "./useMemberships";
import type { CustomerMembership, CustomerMembershipInput } from "./membershipTypes";

const today=()=>new Date().toISOString().slice(0,10);
const addMonth=()=>{const d=new Date();d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,10)};

export function MembershipsPage(){
  const {customers}=useCustomers(); const {plans,memberships,loading,error,refresh,save}=useMemberships();
  const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<CustomerMembership|null>(null);
  const [form,setForm]=useState<CustomerMembershipInput>({customerId:"",planId:"",status:"Active",startDate:today(),renewalDate:addMonth(),loyaltyPoints:0,notes:""});
  const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c])),[customers]); const planMap=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]);
  const filtered=memberships.filter(m=>{const c=customerMap.get(m.customerId);const p=planMap.get(m.planId);return [c?.firstName,c?.lastName,p?.name,m.status].join(" ").toLowerCase().includes(q.toLowerCase())});
  const active=memberships.filter(m=>m.status==="Active").length; const points=memberships.reduce((s,m)=>s+m.loyaltyPoints,0); const recurring=memberships.filter(m=>m.status==="Active").reduce((s,m)=>s+(planMap.get(m.planId)?.price??0),0);
  function begin(m?:CustomerMembership){setEditing(m??null);setForm(m?{customerId:m.customerId,planId:m.planId,status:m.status,startDate:m.startDate,renewalDate:m.renewalDate,loyaltyPoints:m.loyaltyPoints,notes:m.notes}:{customerId:"",planId:plans[0]?.id??"",status:"Active",startDate:today(),renewalDate:addMonth(),loyaltyPoints:0,notes:""});setOpen(true)}
  async function submit(e:FormEvent){e.preventDefault();await save(form,editing?.id);setOpen(false)}
  return <div><section className="page-toolbar"><div className="page-head"><span className="eyebrow">Recurring revenue</span><h1>Memberships & Loyalty</h1><p>Manage care plans, member benefits, renewals, and loyalty points.</p></div><div className="toolbar-actions"><AppButton variant="secondary" onClick={()=>void refresh()}><RefreshCw size={17}/>Refresh</AppButton><AppButton onClick={()=>begin()}>+ Add membership</AppButton></div></section>
  <section className="appointment-summary-grid"><AppCard className="summary-card"><Users size={22}/><div><span>Active members</span><strong>{active}</strong></div></AppCard><AppCard className="summary-card"><Star size={22}/><div><span>Loyalty points</span><strong>{points.toLocaleString()}</strong></div></AppCard><AppCard className="summary-card"><Gift size={22}/><div><span>Plans offered</span><strong>{plans.filter(p=>p.isActive).length}</strong></div></AppCard><AppCard className="summary-card"><Sparkles size={22}/><div><span>Monthly recurring</span><strong>${recurring.toFixed(2)}</strong></div></AppCard></section>
  <section className="membership-plan-grid">{plans.filter(p=>p.isActive).map(p=><AppCard key={p.id} className="membership-plan-card"><span className="plan-frequency">{p.billingFrequency}</span><h3>{p.name}</h3><p>{p.description}</p><strong>${p.price.toFixed(2)}</strong><ul><li>{p.groomingDiscountPercent}% grooming discount</li><li>{p.boardingDiscountPercent}% boarding discount</li><li>{p.includedNailTrims} nail trim(s)</li><li>{p.loyaltyPointsMultiplier}× points</li></ul></AppCard>)}</section>
  <section className="module-controls"><div className="module-search"><Search size={18}/><input placeholder="Search members..." value={q} onChange={e=>setQ(e.target.value)}/></div></section>
  {loading?<div className="module-state"><div className="paw-loader">🐾</div></div>:error?<div className="form-error">{error}</div>:<section className="membership-grid">{filtered.map(m=>{const c=customerMap.get(m.customerId),p=planMap.get(m.planId);return <AppCard key={m.id} className="membership-card"><div><span className={`status-chip status-${m.status.toLowerCase()}`}>{m.status}</span><h3>{c?`${c.firstName} ${c.lastName}`:"Customer"}</h3><p>{p?.name??"Plan"}</p></div><dl><div><dt>Renewal</dt><dd>{m.renewalDate}</dd></div><div><dt>Points</dt><dd>{m.loyaltyPoints}</dd></div><div><dt>Grooming discount</dt><dd>{p?.groomingDiscountPercent??0}%</dd></div><div><dt>Boarding discount</dt><dd>{p?.boardingDiscountPercent??0}%</dd></div></dl><AppButton variant="secondary" onClick={()=>begin(m)}>Edit</AppButton></AppCard>})}</section>}
  {open&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><form className="module-modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">Membership</span><h2>{editing?"Edit membership":"Add membership"}</h2></div></div><div className="form-grid two-column"><label className="field"><span>Customer</span><select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Select customer</option>{customers.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label><label className="field"><span>Plan</span><select required value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Select plan</option>{plans.filter(p=>p.isActive).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as CustomerMembershipInput["status"]})}>{["Active","Paused","Cancelled","Expired"].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Loyalty points</span><input type="number" min="0" value={form.loyaltyPoints} onChange={e=>setForm({...form,loyaltyPoints:Number(e.target.value)})}/></label><label className="field"><span>Start date</span><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label className="field"><span>Renewal date</span><input type="date" value={form.renewalDate} onChange={e=>setForm({...form,renewalDate:e.target.value})}/></label><label className="field full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modal-actions"><AppButton type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</AppButton><AppButton>Save membership</AppButton></div></form></div>}</div>
}
